name: Build and Commit

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This line gives write permission to the workflow
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Update data
        run: pnpm run update-data
      - name: Build
        run: pnpm run build
      - name: Run tests
        run: pnpm test
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff-index --quiet HEAD || git commit -m "🔁 Auto-update data and build"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
